apiVersion: v1
kind: Service
metadata:
  name: shop-svc
  namespace: onlineshop  
spec:
  selector:
    app: onlineshop
  ports:
    - protocol: TCP
      port: 5173   # service port
      targetPort: 5173 #pod port

